### ISSUE TITLE
Logica di base bot

### ISSUE THREAD

**Issue by armaDio** [GabrieleMaurina/Deasy#1]
L'utente deve poter inserire un comando e ottenere una risposta statica.
Gli argomenti trattabili dovranno riguardare: tirocinio, erasmus, tesi, tasse, mensa.
Dovrà anche essere possibile utilizzare un comando help per elencare gli altri possibili comandi.

**Comment by Marvash** [comment]
Per testare questa feature l'utente può inserire uno ad uno i comandi "tirocinio", "erasmus", "tesi", "tasse", "mensa" e "help" e verificare che per ognuno di essi gli venga restituita una riposta pertinente.
